// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyStore.proto

package io.grpc.keystore;

public interface GetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:keystore.GetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
