// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyStore.proto

package io.grpc.keystore;

public final class KeyStoreProto {
  private KeyStoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keystore_PutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_keystore_PutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keystore_PutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_keystore_PutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keystore_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_keystore_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keystore_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_keystore_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keystore_GetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_keystore_GetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keystore_KeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_keystore_KeyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016KeyStore.proto\022\010keystore\"(\n\nPutRequest" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"5\n\013PutRespo" +
      "nse\022\017\n\007success\030\001 \001(\010\022\025\n\rmessageStatus\030\002 " +
      "\001(\t\"\031\n\nGetRequest\022\013\n\003key\030\001 \001(\t\"\034\n\013GetRes" +
      "ponse\022\r\n\005value\030\001 \001(\t\"\017\n\rGetAllRequest\"\033\n" +
      "\013KeyResponse\022\014\n\004name\030\001 \001(\t2\270\001\n\010KeyStore\022" +
      "4\n\003put\022\024.keystore.PutRequest\032\025.keystore." +
      "PutResponse\"\000\0224\n\003get\022\024.keystore.GetReque" +
      "st\032\025.keystore.GetResponse\"\000\022@\n\ngetAllKey" +
      "s\022\027.keystore.GetAllRequest\032\025.keystore.Ke" +
      "yResponse\"\0000\001B(\n\020io.grpc.keystoreB\rKeySt" +
      "oreProtoP\001\242\002\002KVb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_keystore_PutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_keystore_PutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_keystore_PutRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_keystore_PutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_keystore_PutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_keystore_PutResponse_descriptor,
        new java.lang.String[] { "Success", "MessageStatus", });
    internal_static_keystore_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_keystore_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_keystore_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_keystore_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_keystore_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_keystore_GetResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_keystore_GetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_keystore_GetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_keystore_GetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_keystore_KeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_keystore_KeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_keystore_KeyResponse_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
