// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyStore.proto

package io.grpc.keystore;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:keystore.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
