// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyStore.proto

package io.grpc.keystore;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:keystore.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
