// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyStore.proto

package io.grpc.keystore;

public interface PutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:keystore.PutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string messageStatus = 2;</code>
   * @return The messageStatus.
   */
  java.lang.String getMessageStatus();
  /**
   * <code>string messageStatus = 2;</code>
   * @return The bytes for messageStatus.
   */
  com.google.protobuf.ByteString
      getMessageStatusBytes();
}
